#!/bin/bash
# Made by Joy+fox

echo "
  ______          _            __   __
 |___  /         | |           \ \ / /
    / / __ _ _ __| | _____  ___ \ V / 
   / / / _\` | '__| |/ / _ \/ __| > <  
  / /_| (_| | |  |   < (_) \__ \/ . \ 
 /_____\__,_|_|  |_|\_\___/|___/_/ \_\


                  ZarkosX
"

git clone https://github.com/dragonlabsdev/v2panel

curl -sL https://deb.nodesource.com/setup_23.x | sudo bash -

apt-get install nodejs git

cd v2panel

apt install zip -y && unzip panel.zip && cd panel

npm install && npm run seed && npm run createUser


