#!/bin/bash
# Made by Joy+fox

echo "📦 Installing Draco Panel Auto Update with Docker...
       _____         
      |  ___|____  __
      | |_ / _ \ \/ /
      |  _| (_) >  < 
      |_|  \___/_/\_\

"

git clone https://github.com/dragonlabsdev/v2panel
curl -sL https://deb.nodesource.com/setup_23.x | sudo bash -
apt-get install nodejs git
cd v2panel
apt install zip -y && unzip panel.zip && cd panel
npm install && npm run seed && npm run createUser
node .
