#!/bin/bash
# Made by Joy+ZarkosX

echo "📦 Installing Pterodactyl wings update v1.11.13 with Docker...
  ______          _            __   __
 |___  /         | |           \ \ / /
    / / __ _ _ __| | _____  ___ \ V / 
   / / / _\` | '__| |/ / _ \/ __| > <  
  / /_| (_| | |  |   < (_) \__ \/ . \ 
 /_____\__,_|_|  |_|\_\___/|___/_/ \_\


                  ZarkosX
"


git clone https://github.com/draco-labes/draco-daemon
cd draco-daemon
npm install
